NUMPY

In [ ]:
import numpy as np 
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])


In [2]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [3]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [4]:
data+data


array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [5]:
data.shape

(2, 3)

In [9]:
data.dtype


dtype('float64')

In [10]:
###Creating ndarraysabs
data1 = [1,2,3,4,5]

In [11]:
arr= data1

In [12]:
arr

[1, 2, 3, 4, 5]

In [13]:
arr1 = np.array(data1)
arr1
array([6. , 7.5, 8. , 0. , 1. ])

NameError: name 'array' is not defined

In [14]:
arr1 = np.array(data1)


In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
array([6. , 7.5, 8. , 0. , 1. ])

NameError: name 'array' is not defined

In [17]:
 data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
def lesseroftwoevents(a,b):
pass:

IndentationError: expected an indented block after function definition on line 1 (4226701680.py, line 2)

In [24]:
def lesseroftwoevents(a,b):
pass:

IndentationError: expected an indented block after function definition on line 1 (4226701680.py, line 2)

In [26]:
def lesse_rof_twoevents(a,b):
    pass:

SyntaxError: invalid syntax (124926213.py, line 2)

In [28]:
def dog(name):
pass

IndentationError: expected an indented block after function definition on line 1 (2256911784.py, line 2)

In [29]:
def dog(name):
    pass
    

In [30]:
dog('smiggle')

In [31]:
dog

<function __main__.dog(name)>